import Navbar from "../components/Navbar"
import ExtractionList from '../components/ExtractionList'
import Head from 'next/head'

import axios from "axios";
import {useCookies} from 'react-cookie';
import {useEffect, useState} from 'react'
import {useTokenContext} from '../components/TokenContext'

export default function History() {
    let baseURL = 'http://localhost:8000';

    const [cookies] = useCookies();

    const tokenPreflight = useTokenContext();

    const [extractions, setExtractions] = useState({
        extractions:[{}],
    });
    const [isLoaded, setIsLoaded] = useState(false)

    useEffect(() => {
        tokenPreflight()
        axios.get(baseURL + '/extractions/', {
            headers: {
                'Authorization': `Bearer ${cookies['access']}`,
                'Content-Type': 'application/json'
            }
        }).then((res)=> {
            let data= res.data.results
            return data
        }).then((data) => {
            setExtractions(data);
            setIsLoaded(true);
        });
    }, []);

    return(
        <>
            <Head>
              <title>Create Next App</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar/>
            <div className='absolute flex flex-col top-0 right-0 w-5/6 h-screen items-center justify-center text-center'>
              {isLoaded &&<ExtractionList extractions={extractions}/>}
            </div>
        </>
    )
}
